---
- hosts: Docker
  vars_prompt:
  - name: "Centos_Version"
    prompt: "CentOS Release Version"
    default: "7.3"
    private: no
  - name: "Docker_EE_URL"
    prompt: "Enter your Docker EE Docker"
    private: no

  tasks:
    - name: Update Packages
      yum: name='*' state=latest

    - name: Copy Hosts File
      copy: src="/etc/hosts" dest="/etc/hosts"

    - name: Open port 443
      command: firewall-cmd --permanent --zone=public --add-port=443/tcp
    - name: Open ports 2375-2376
      command: firewall-cmd --permanent --zone=public --add-port=2375-2376/tcp
    - name: Open port 4789/tcp
      command: firewall-cmd --permanent --zone=public --add-port=4789/tcp
    - name: Open port 4789/udp
      command: firewall-cmd --permanent --zone=public --add-port=4789/udp
    - name: Open ports 12379-12385/tcp
      command: firewall-cmd --permanent --zone=public --add-port=12379-12385/tcp
    - name: Open ports 2377/tcp
      command: firewall-cmd --permanent --zone=public --add-port=2377/tcp
    - name: Open ports 7946/tcp
      command: firewall-cmd --permanent --zone=public --add-port=7946/tcp
    - name: Open ports 7946/udp
      command: firewall-cmd --permanent --zone=public --add-port=7946/udp
    - name: Open ports 12386/tcp
      command: firewall-cmd --permanent --zone=public --add-port=12386/tcp
    - name: Open ports 12387/tcp
      command: firewall-cmd --permanent --zone=public --add-port=12387/tcp
    - name: Open ports 12376/tcp
      command: firewall-cmd --permanent --zone=public --add-port=12376/tcp

    - name: Restart Firewall Services
      service: name=firewalld state=restarted

    - name: Create Docker URL File
      shell: sh -c 'echo "{{Docker_EE_URL}}/centos" > /etc/yum/vars/dockerurl'
    - name: Create Docker Version File
      shell: sh -c 'echo "{{Centos_Version}}" > /etc/yum/vars/dockerosversion'

    - name: Install Yum Utils
      yum: name=yum-utils state=present

    - name: Configure Docker EE Repo
      shell: "yum-config-manager --add-repo '{{Docker_EE_URL}}/docker-ee.repo' update_cache=yes"

    - name: Install Docker EE  
      yum: name=docker-ee state=present

    - name: Enable Docker Services
      shell: "/usr/bin/systemctl enable docker.service"

    - name: Start Docker Services
      shell: "/usr/bin/systemctl start docker.service"
